name: Library Build And Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build library with gradle
        env:
          AWS_S3_ACCESSKEY: ${{ secrets.AWS_S3_ACCESSKEY }}
          AWS_S3_SECRETKEY: ${{ secrets.AWS_S3_SECRETKEY }}
        run: |
          make maven
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Extract current version
        id: get_version
        run: |
          CURRENT_VERSION=$(cat version | awk '{$1=$1;print}')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      - name: Send Notification To Slack
        run: |
          curl -H 'Content-type: application/json' -X POST -d "{'text': 'New android walletkit lib v${{env.CURRENT_VERSION}} is out.'}" ${{secrets.CLIENTS_WEBHOOK}}
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
