name: Start Library Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Start The Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # NOTE @v2 uses the token as an auth http header. Set it to
          # a Personal Access Token instead of secrets.GITHUB_TOKEN
          # so that tag pushes trigger repo push events.
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Start The Release
        run: make release
